name: Build GH Pages

on:
  workflow_call:

jobs:
  initialize:
    name: Checkout and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/lock.json') }}

      - name: Fetch deno dependencies
        run: deno cache lib/deps.ts lib/dev_deps.ts

      - name: Build Public files
        run: deno task build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

  deploy_public_assets:
    name: Deploy public assets
    runs-on: ubuntu-latest
    needs: initialize
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
