name: Tests and Lints packages

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache deno dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/lock.json') }}

      - name: Fetch deno dependencies
        run: deno cache lib/deps.ts lib/dev_deps.ts

      - name: Run linting
        run: |
          deno fmt --check
          deno lint
